version: 2

jobs:
  jobA:
    image: screwdrivercd/noop-container
    requires: [ ~commit ]
    steps:
        - setup-scm: echo no-op
    annotations:
      screwdriver.cd/virtualJob: true
    
  jobB:
    image: node:20
    requires: [~jobA]
    steps:
        - keep-running: |
            sleep 5
    
  jobC:
    image: screwdrivercd/noop-container
    requires: [ ~jobB ]
    steps:
        - setup-scm: echo no-op
    annotations:
      screwdriver.cd/virtualJob: true
    blockedBy: [ ~jobD ]
    
  jobD:
    image: node:20
    requires: [~jobC]
    steps:
        - keep-running: |
            sleep 120
