version: 2

jobs:
  jobA:
    image: screwdrivercd/noop-container
    requires: [ ~jobB ]
    steps:
        - setup-scm: echo no-op
    annotations:
      screwdriver.cd/virtualJob: true
    blockedBy: [ ~jobC ]
    
  jobB:
    image: node:20
    requires: [~commit]
    steps:
        - keep-running: |
            sleep 10
    freezeWindows: ['* 0-4 ? * *']
  jobC:
    image: node:20
    requires: [~jobA]
    steps:
        - keep-running: |
            sleep 30
