version: 2

jobs:
  jobA:
    image: screwdrivercd/noop-container
    requires: [ ~commit ]
    steps:
        - setup-scm: echo no-op
    annotations:
      screwdriver.cd/virtualJob: true
    blockedBy: [ ~jobB ]
    freezeWindows: ['* 0-20 ? * *']
    
  jobB:
    image: node:20
    requires: [~jobA]
    steps:
        - keep-running: |
            sleep 60
    freezeWindows: ['* 0-3 ? * *']
  jobC:
    image: node:20
    requires: [~jobB]
    steps:
        - keep-running: |
            sleep 30
